# ----------------------------------------------------------------------------
# Customize Options: Must Change
#
# Title:
title: Spring을 이용한 객체지향 스터디

# Where the page will be deployed.
# If it's https://foo.com/bar, just write "https://foo.com"
url: "https://5pecia1.github.io"
# url: "https://6698cae12ead42f9809d8b4de1f8f347.vfs.cloud9.ap-southeast-1.amazonaws.com/"

# If you're deployging to a subdirectory (https://foo.com/bar/)
# Then write "/bar/". Otherwise, remove this line.
baseurl: "/spring-study/"
# baseurl: ""

# Twitter IDs
# twitter:
#   username: "chibicode"
# author:
#   twitter: "chibicode"

# Set default og:image
# From Unsplash: https://unsplash.com/photos/1_CMoFsPfso
defaults:
  -
    scope:
      path: ""
    values:
      image: "static/images/spring-logo.png"

# ----------------------------------------------------------------------------
# Customize Options: Optional
#
# See: https://material.io/guidelines/style/color.html
# Use color-name-value, like pink-200 or deep-purple-100
brand_color: "light-green-500"

# How article URLs are structured.
# See: https://jekyllrb.com/docs/permalinks/
permalink: posts/:title/

# "UA-NNNNNNNN-N"
google_analytics: "UA-115161414-2"

# Language. For example, if you write in Japanese, use "ja"
lang: "ko"

# How many posts are visible on the home page without clicking "View More"
num_posts_visible_initially: 5

# Date format: See http://strftime.net/
date_format: "%Y %m %-d"
# ----------------------------------------------------------------------------

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - mix-manifest.json
  - webpack.mix.js
  - yarn.lock
  - package.json
  - hot
  - LICENSE.txt

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-readme-index
